# MySQL service for internal access
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
spec:
  selector:
    app: wordpress-mysql
  ports:
    - port: 3306
  # ClusterIP makes it only reachable within the GKE cluster
  type: ClusterIP
